version 1.0.0
FullstackAcademy/2007-catchers-in-the-rye pull request #14
Opened 2020-10-24 16:58 UTC by fugoto

Core models Costume, User, Category, Order defined and seeded
Basic routes on all models set up
Redux store / Provider initiated
React components set up for Home 'localhost:3000/home' and Costumes 'localhost:3000/costumes'
Very cool navbar set up but not displayed for now

2020-10-27 00:07 UTC, peetklecha commented on server/db/index.js
> +
small thing but why are these named exports?

2020-10-27 00:07 UTC, peetklecha commented on server/db/models/Order.js
> +    ccNumber: {
are you sure you wanna store credit card numbers like this? relatedly, have you at all looked into how you are going to implement payment (e.g., stripe?) and how that would bear on this choice?

2020-10-27 00:07 UTC, peetklecha commented on server/db/index.js
> +//import your db
clear out all these boilerplate comments

2020-10-28 00:43 UTC, leafoflegend requested changes
Bunch of things that I found in here.

Only critical thing is that you are leaking user data. We cannot merge this code with that security hole.

I couldn't find the relations between your models. I have mixed feelings about them right now - but it may work well. Hard to tell without seeing relations.

Linting needs to be standardized.

See comments for more.

2020-10-28 00:43 UTC, leafoflegend commented on .gitignore
> +.DS_Store
Don't yall use vscode? Shouldn't you ignore all the files it adds?

2020-10-28 00:43 UTC, leafoflegend commented on README.md
> +
👍

2020-10-28 00:43 UTC, leafoflegend commented on client/components/Cart.js
> +    constructor(){
This is unnecessary and also, wrong. By default, in Javascript, classes without explicit constructors defined will default to

```javascript
function defaultConstructor(...args) {
  super(...args);
}
```

If anything, this is causing issues because you are not passing the `props` into `super`, causing inheritance to malfunction.

2020-10-28 00:43 UTC, leafoflegend commented on client/components/Cart.js
> +        const cart = this.props.cart
Probably a good opportunity to use destructuring.

2020-10-28 00:43 UTC, leafoflegend commented on client/components/Home.js
> +import React, { Component } from "react";
Linting standards are inconsistent. Single quotes in previous file, double quotes here. Please choose one and stick with it.

2020-10-28 00:43 UTC, leafoflegend commented on client/components/authentication/CreateUser.js
> +    <>
Dank.

2020-10-28 00:43 UTC, leafoflegend commented on client/components/authentication/UserInfo.js
> +          if(this.props.type === 'login') response = (await axios.post('/api/auth/login',this.state)).data
We use thunks elsewhere, why not here?

2020-10-28 00:43 UTC, leafoflegend commented on client/components/category/SingleCategory.js
> +    //this.props.selectCategory(this.props.selectedId)
?

2020-10-28 00:43 UTC, leafoflegend commented on client/components/category/SingleCategory.js
> +    // should be fleshed out more based on api routes to include all costumes belonging to a category
Label comments like these `// TODO: {task_here}` - editors support this and will allow you to quickly find them.

2020-10-28 00:43 UTC, leafoflegend commented on client/components/costume/CreateCostume.js
> +        super()
Please pass props to `super`.

2020-10-28 00:43 UTC, leafoflegend commented on client/components/costume/CreateCostume.js
> +        const { state, props } = this
Whats the story with semicolons? Do we use them or not?

2020-10-28 00:43 UTC, leafoflegend commented on client/components/index.js
> +          <Route path= "/cart" exact component={Cart} />
No default route?

2020-10-28 00:43 UTC, leafoflegend commented on client/redux/actions/loadCostumes.js
> +    return await axios
`return await` does nothing. What is the difference with/without `await` here?

2020-10-28 00:43 UTC, leafoflegend commented on client/redux/index.js
> +
Two lines of padding here?

2020-10-28 00:43 UTC, leafoflegend commented on client/redux/singleCategory.js
> +      const response = await axios.get(`/api/categories/${id}`);
All uncertainty should be managed with `try catch`

2020-10-28 00:43 UTC, leafoflegend commented on package.json
> +    "test": "NODE_ENV='test' mocha  ./tests --recursive --watch --require @babel/polyfill --require @babel/register",
`jest` is superior 👑

2020-10-28 00:43 UTC, leafoflegend commented on package.json
> +    "start": "echo 'Running server for production - developers, use npm run start-dev for development' && node seed && node server",
fun

2020-10-28 00:43 UTC, leafoflegend commented on package.json
> +    "postinstall": "webpack"
Don't need both - this will cause heroku to double build.

2020-10-28 00:43 UTC, leafoflegend commented on seed.js
> +        await Order.bulkCreate(orders)
Can any of these be parallelized?

2020-10-28 00:43 UTC, leafoflegend commented on seed.js
> +        const costumesCreated = await Costume.findAll()
These three can definitely be parallelized.

2020-10-28 00:43 UTC, leafoflegend commented on server/api/authentication.js
> +const A_WEEK_IN_SECONDS = 60 * 60 * 24 * 7;
i think it may indeed prefer ms - i think this may cause bugs

2020-10-28 00:43 UTC, leafoflegend commented on server/api/authentication.js
> +router.post('/login', async(req,res,next)=> {
this all looks very similar 🔍 👁️

2020-10-28 00:43 UTC, leafoflegend commented on server/api/order.js
> +        res.send(order)
Any user can view any order if they have the order id? Aren't there some privacy concerns with that?

2020-10-28 00:43 UTC, leafoflegend commented on server/api/user.js
> +router.get('/', async(req, res, next) => {
These are **enormous security violations.** You are allowing anybody to fetch all your users information - **including passwords!** These routes need to be locked down and/or removed.

2020-10-28 00:43 UTC, leafoflegend commented on server/db/models/Order.js
> +    shippingAddress: {
I do ponder the relationship between orders and addresses a bit here...

2020-10-28 00:43 UTC, leafoflegend commented on server/index.js
> +app.use(express.urlencoded( {extended: false} ))
why

2020-10-28 00:43 UTC, leafoflegend commented on server/public/index.html
> +  <!-- <link rel="stylesheet" href="../../../css/mystyles.css"> -->
?

2020-10-28 00:43 UTC, leafoflegend commented on test/tests.js
> +//where we write tests
cute

2020-10-28 00:43 UTC, leafoflegend commented on .gitignore
> +server/public/bundle.js
Needs to be improved to hide all the content hashed build artifacts

2020-11-06 01:19 UTC, closed without merging

2020-11-06 01:19 UTC, Djmiller1717 commented
making new pull request.